### ISSUE TITLE
An ambiguity in functionality description in REAMDE.MD

### ISSUE THREAD

**Issue by MostHappyCougar** [BoolmanO/pyjsv#2]
Detected in commit: [fd04bcb](https://github.com/BoolmanO/pyjsv/commit/fd04bcb82527b9e1149f6ad92ab42af25209e000)

**Description**
According to functionality description in README.MD:
> This library is the easiest way to manipulate data through multiple formats, xml, toml, yaml, json. They are all serialized to dict

This library is making possible *to manipulate* data. As per current functionality description and wording *to manipulate data* we are expecting to following questions have been clarified:
1. What's exasctly means *to manipulate data through multiple formats*. Does it means:
-  We could parse xml, toml, yaml, json files?
-  We could amend an existing file upon these formats?
-  We could create a new file with any of these formats?
2. What's exacly means *They are all serialized to dict*?

**Comment by BoolmanO** [comment]
I updated the documentation, does this solve your problem?

**Comment by MostHappyCougar** [comment]
Hi, @BoolmanO!
As per updates specification section: `Docs` mentioned questions have been clarified. This ticket can be closed
Thanks,
Alejandro
