### ISSUE TITLE
Misalignments between functionality overview and using cases in README.MD

### ISSUE THREAD

**Issue by MostHappyCougar** [BoolmanO/pyjsv#3]
Detected in commit: [fd04bcb](https://github.com/BoolmanO/pyjsv/commit/fd04bcb82527b9e1149f6ad92ab42af25209e000)

**Description:**
According to the README.MD: `(At the moment we only have json format)`, but in `Usage/Examples` section of this document exist example `SimpleXml` that relatet to XML files.

Could you pls clarify whether part of description is correct, the section `Usage/Examples` of phrase `(At the moment we only have json format)`? Could you pls correct README.MD accordingly

**Comment by BoolmanO** [comment]
Hello, I saw your confusion, yes, I made a mistake according to Freud, I apologize for the inconvenience caused. README.md has been fixed!
